/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lol;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.button.StandardButtonShaper;

/**
 *
 * @author Zoidiano
 */
public class frm_tabla extends javax.swing.JFrame {

    /**
     * Creates new form frm_tabla
     */
    int seleccion1_a=0,seleccion1_b=0,seleccion1_c=0,seleccion1_d=0;
    int seleccion2_a=0,seleccion2_b=0;
    int seleccion3=0;
    public frm_tabla() {
        initComponents();
        frm_tabla.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.CremeSkin");
        this.btn1.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn2.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn3.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn4.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn5.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn6.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn7.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn8.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn9.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn10.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn11.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn12.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn13.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn14.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btn15.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn13 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        backsup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel2.setText("Cuartos de Final");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel3.setText("Semifinales");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel4.setText("Final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel5.setText("Semifinales");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel6.setText("Cuartos de Final");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        btn13.setText(" ");
        btn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn13MouseClicked(evt);
            }
        });
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        getContentPane().add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 130, 30));

        btn2.setText(" ");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        btn4.setText(" ");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4MouseExited(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 130, 30));

        btn8.setText(" ");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn8MouseExited(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 130, 30));

        btn9.setText(" ");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 30));

        btn11.setText(" ");
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn11MouseClicked(evt);
            }
        });
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, 30));

        btn7.setText(" ");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn7MouseExited(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 130, 30));

        btn6.setText(" ");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn6MouseExited(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 130, 30));

        btn5.setText(" ");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 130, 30));

        btn1.setText(" ");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        btn10.setText(" ");
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10MouseClicked(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, 30));

        btn12.setText(" ");
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn12MouseClicked(evt);
            }
        });
        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 130, 30));

        btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lol/first33 (2).png"))); // NOI18N
        btn15.setText(" ");
        getContentPane().add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 130, 60));

        btn3.setText(" ");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 30));

        btn14.setText(" ");
        btn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn14MouseClicked(evt);
            }
        });
        getContentPane().add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 130, 30));

        backsup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lol/back.png"))); // NOI18N
        getContentPane().add(backsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lol/john_cena-ConvertImage.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 260, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
          int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
                if(seleccion1_d!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_d=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn11.setText("quien sera ¬¬ ...?");
                }else
                {
                btn11.setText(btn5.getText());
                seleccion1_d=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
           int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
                if(seleccion1_d!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_d=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn11.setText("quien sera ¬¬ ...?");
                }else
                {
                btn11.setText(btn6.getText());
                seleccion1_d=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
                 if(seleccion1_c!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_c=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn12.setText("quien sera ¬¬ ...?");
                }else
                {
                btn12.setText(btn7.getText());
                seleccion1_c=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
              if(seleccion1_c!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_c=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn12.setText("quien sera ¬¬ ...?");
                }else
                {
                btn12.setText(btn8.getText());
                seleccion1_c=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn8MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
           int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
              if(seleccion1_b!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_b=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn10.setText("quien sera ¬¬ ...?");
                }else
                {
                btn10.setText(btn4.getText());
                seleccion1_b=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn4MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
           int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
              if(seleccion1_b!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_b=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn10.setText("quien sera ¬¬ ...?");
                }else
                {
                btn10.setText(btn3.getText());
                seleccion1_b=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn3MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
           int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
              if(seleccion1_a!=0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_a=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn9.setText("quien sera ¬¬ ...?");
                }else
                {
                btn9.setText(btn2.getText());
                seleccion1_a=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn2MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        int seleccion = JOptionPane.showOptionDialog(
        this,
        "¿Desea Coronarlo Ganador?",
        "Seleccione una opción",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[] { "Si", "No"},
        "Si");
        if (seleccion != -1)
        {
            if((seleccion + 1)==1)
            {
                if(seleccion1_a>0)
                {
                JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                seleccion1_a=0;
                JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                btn9.setText("quien sera ¬¬ ...?");
                }else
                {
                btn9.setText(btn1.getText());
                seleccion1_a=1;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Falto Pepsi");
            }
        }
    }//GEN-LAST:event_btn1MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        if(seleccion1_a!=0)
        {
            int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Coronarlo Ganador?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "Si", "No"},
            "Si");
            if (seleccion != -1)
            {
                if((seleccion + 1)==1)
                {
                    if(seleccion2_a>0)
                    {
                    JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                    seleccion2_a=0;
                    JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                    btn13.setText("quien sera ¬¬ ...?");
                    }else
                    {
                    btn13.setText(btn9.getText());
                    seleccion2_a=1;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Falto Pepsi");
                }
            }
        }else
        {
        JOptionPane.showMessageDialog(null, "Selecciona el Ganador  Anterior primero");
        }
    }//GEN-LAST:event_btn9MouseClicked

    private void btn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseClicked
        if(seleccion1_b!=0)
        {
            int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Coronarlo Ganador?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "Si", "No"},
            "Si");
            if (seleccion != -1)
            {
                if((seleccion + 1)==1)
                {
                    if(seleccion2_a>0)
                    {
                    JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                    seleccion2_a=0;
                    JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                    btn13.setText("quien sera ¬¬ ...?");
                    }else
                    {
                    btn13.setText(btn10.getText());
                    seleccion2_a=1;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Falto Pepsi");
                }
            }
        }else
        {
        JOptionPane.showMessageDialog(null, "Selecciona el Ganador  Anterior primero");
        }
    }//GEN-LAST:event_btn10MouseClicked

    private void btn11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MouseClicked
         if(seleccion1_d!=0)
        {
            int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Coronarlo Ganador?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "Si", "No"},
            "Si");
            if (seleccion != -1)
            {
                if((seleccion + 1)==1)
                {
                    if(seleccion2_b>0)
                    {
                    JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                    seleccion2_b=0;
                    JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                    btn14.setText("quien sera ¬¬ ...?");
                    }else
                    {
                    btn14.setText(btn11.getText());
                    seleccion2_b=1;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Falto Pepsi");
                }
            }  
            
        }else
        {
        JOptionPane.showMessageDialog(null, "Selecciona el Ganador  Anterior primero");
        }
    }//GEN-LAST:event_btn11MouseClicked

    private void btn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseClicked
        if(seleccion1_c!=0)
        {
          int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Coronarlo Ganador?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "Si", "No"},
            "Si");
            if (seleccion != -1)
            {
                if((seleccion + 1)==1)
                {
                    if(seleccion2_b>0)
                    {
                    JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                    seleccion2_b=0;
                    JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                    btn14.setText("quien sera ¬¬ ...?");
                    }else
                    {
                    btn14.setText(btn12.getText());
                    seleccion2_b=1;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Falto Pepsi");
                }
            }  
        }else
        {
        JOptionPane.showMessageDialog(null, "Selecciona el Ganador  Anterior primero");
        }
    }//GEN-LAST:event_btn12MouseClicked

    private void btn13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn13MouseClicked
   if(seleccion1_a>0 &&  seleccion2_a>0 && seleccion1_b>0)
    {
            int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Coronarlo Ganador?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "Si", "No"},
            "Si");
            if (seleccion != -1)
            {
                if((seleccion + 1)==1)
                {
                    if(seleccion3>0)
                    {
                    JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                    seleccion3=0;
                    JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                    btn15.setText("quien sera ¬¬ ...?");
                    }else
                    {
                    btn15.setText(btn13.getText());
                    seleccion3=1;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Falto Pepsi");
                }
            } 
    }
   else
    {
        JOptionPane.showMessageDialog(null, "Selecciona el Ganador  Anterior primero");
    }
    }//GEN-LAST:event_btn13MouseClicked

    private void btn14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn14MouseClicked
    if(seleccion1_c>0 &&  seleccion2_b>0 && seleccion1_d>0)
    {
            int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Coronarlo Ganador?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "Si", "No"},
            "Si");
            if (seleccion != -1)
            {
                if((seleccion + 1)==1)
                {
                    if(seleccion3>0)
                    {
                    JOptionPane.showMessageDialog(null,":O Te equivocaste no te preocupes yo lo arreglo");
                    seleccion3=0;
                    JOptionPane.showMessageDialog(null, "Elige de nuevo nomas");
                    btn15.setText("quien sera ¬¬ ...?");
                    }else
                    {
                    btn15.setText(btn14.getText());
                    seleccion3=1;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Falto Pepsi");
                }
            }         
    }
   else
    {
        JOptionPane.showMessageDialog(null, "Selecciona el Ganador  Anterior primero");
    }
    }//GEN-LAST:event_btn14MouseClicked

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
     btn1.setForeground(Color.blue);
    }//GEN-LAST:event_btn1MouseEntered

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
    btn2.setForeground(Color.blue);
    }//GEN-LAST:event_btn2MouseEntered

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
    btn3.setForeground(Color.blue);
    }//GEN-LAST:event_btn3MouseEntered

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
    btn4.setForeground(Color.blue);
    }//GEN-LAST:event_btn4MouseEntered

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
    btn5.setForeground(Color.blue);
    }//GEN-LAST:event_btn5MouseEntered

    private void btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseEntered
    btn6.setForeground(Color.blue);
    }//GEN-LAST:event_btn6MouseEntered

    private void btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseEntered
     btn7.setForeground(Color.blue);
    }//GEN-LAST:event_btn7MouseEntered

    private void btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseEntered
    btn8.setForeground(Color.blue);
    }//GEN-LAST:event_btn8MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
    btn1.setForeground(Color.black);
    }//GEN-LAST:event_btn1MouseExited

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
    btn2.setForeground(Color.black);
    }//GEN-LAST:event_btn2MouseExited

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        btn3.setForeground(Color.black);
    }//GEN-LAST:event_btn3MouseExited

    private void btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseExited
        btn4.setForeground(Color.black);
    }//GEN-LAST:event_btn4MouseExited

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
        btn5.setForeground(Color.black);
    }//GEN-LAST:event_btn5MouseExited

    private void btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseExited
        btn6.setForeground(Color.black);
    }//GEN-LAST:event_btn6MouseExited

    private void btn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseExited
        btn7.setForeground(Color.black);
    }//GEN-LAST:event_btn7MouseExited

    private void btn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseExited
        btn8.setForeground(Color.black);
    }//GEN-LAST:event_btn8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backsup;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn10;
    public javax.swing.JButton btn11;
    public javax.swing.JButton btn12;
    public javax.swing.JButton btn13;
    public javax.swing.JButton btn14;
    public javax.swing.JButton btn15;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
