/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lol;

import java.awt.event.KeyEvent;
import java.util.Random;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Zoidiano
 */
public class frm_ingreso extends javax.swing.JFrame {

    /**
     * Creates new form frm_ingreso
     */
    frm_tabla f = new frm_tabla();
    int contador = 1;
    String guardadorv = "";
    String guardador = "";
    int n = 0, t = 0;

    public frm_ingreso() {
        initComponents();
        cazuela();
    }

    public void cazuela() {
        int[] ndigitos = new int[10]; // arreglo para guardar numeros distintos al azar 
        int total = 0; // auxiliar para saber cuantos numeros se han agregado 
        int nuevo = 0; // numero al azar 
        int aux = 0;// auxiliar para comparar el numero antes de guardarlo  
        Random r = new Random();// construir random
        do // agregar numeros mientras el total sea menor a 10 
        {   nuevo = r.nextInt(8) + 1; // crear numero entero al azar entre 0 y 9  // nextInt(valorMaximoACrear+1) 
            for (int i = 0; i < total; i++) {// recorrer la lista de los valores ya guardados 
                // si el nuevo numero existe en la posicion actual 
                if (nuevo == ndigitos[i]) {
                    aux = 1;
                }
            }
            // si al terminar de recorrer la lista no se encontro otro igual 
            if (aux == 0) {
                // agregar en la siguiente posicion el nuevo numero 
                ndigitos[total] = nuevo;
                total++;
            }
            // reestablecer comparador 
            aux = 0;
        } while (total < 8);
        // imprime los resultados 
        for (int i = 0; i < 8; i++) {
            guardador = guardador + (ndigitos[i] + ",").replace(",", "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion de Equipos");

        jLabel1.setText("NOMBRES EQUIPOS:");

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtarea.setRows(5);
        txtarea.setEnabled(false);
        jScrollPane2.setViewportView(txtarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(txt1))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (contador > 8) {

            }else {
                guardadorv = guardador.substring(t, contador);
                
                n = Integer.parseInt(guardadorv);
                txtarea.setText(txtarea.getText() + "#" + this.txt1.getText() + "\n");
                switch (n) {
                    case 1:
                        f.btn8.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 2:
                        f.btn5.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 3:
                        f.btn1.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 4:
                        f.btn3.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 5:
                        f.btn2.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 6:
                        f.btn6.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 7:
                        f.btn4.setText(this.txt1.getText().toUpperCase());
                        break;
                    case 8:
                        f.btn7.setText(this.txt1.getText().toUpperCase());
                        break;
                    default:
                        break;
                }
                contador++;
                t++;
                if (contador > 8) {
                    dispose();
                    JOptionPane.showMessageDialog(rootPane, "Teams Completos seras derivado a la tabla de posiciones");
                    f.setLocationRelativeTo(null);
                    f.setVisible(true);

                }
                this.txt1.setText("");
            }
        }
    }//GEN-LAST:event_txt1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
